KEY_ESCAPE = 27

REGION_WIDTH = 27
REGION_HEIGHT = 10
MIN_ROOM_WIDTH = 6
MAX_ROOM_WIDTH = (REGION_WIDTH - 2)
MIN_ROOM_HEIGHT = 5
MAX_ROOM_HEIGHT = (REGION_HEIGHT - 2)

ROOMS_IN_WIDTH = 3
ROOMS_IN_HEIGHT = 3
ROOMS_NUM = ROOMS_IN_WIDTH * ROOMS_IN_HEIGHT
MAX_CORRIDOR_PARTS = 3
MAX_CORRIDORS_NUM = (ROOMS_NUM - 1) * MAX_CORRIDOR_PARTS

MAP_HEIGHT = ROOMS_IN_HEIGHT * REGION_HEIGHT + 7
MAP_WIDTH = ROOMS_IN_WIDTH * REGION_WIDTH

TERM_HEIGHT = MAP_HEIGHT + 5
TERM_WIDTH = MAP_WIDTH + 5 + 10

INIT_MONSTERS_STRENGTH_PER_LEVEL = 150
COEFF_UPDATE_STRENGTH_MONSTERS_PER_LEVEL = 45

MIN_MONSTERS_PER_LEVEL = 4
MAX_MONSTERS_PER_ROOM = 2
MAX_CONSUMABLES_PER_ROOM = 3
LEVEL_UPDATE_DIFFICULTY = 10
PERCENTS_UPDATE_DIFFICULTY_MONSTERS = 2

MIN_INCREASE = 1
MAX_PERCENT_HEALTH_REGEN = 20
MAX_PERCENT_AGILITY_INCREASE = 10
MAX_PERCENT_STRENGTH_INCREASE = 10

MIN_ELIXIR_DURATION_SECONDS = 30
MAX_ELIXIR_DURATION_SECONDS = 60

MIN_WEAPON_STRENGTH = 30
MAX_WEAPON_STRENGTH = 50

MAX_ITEM_COUNT_IN_BACKPACK = 9

MAX_GAME_LEVEL = 21

MAX_TRIES_TO_MOVE = 16

INITIAL_HIT_CHANCE = 70
STANDART_AGILITY = 50
AGILITY_FACTOR = 0.3
INITIAL_DAMAGE = 30
STANDART_STRENGTH = 50
STRENGTH_FACTOR = 0.3
STRENGTH_ADDITION = 65
SLEEP_CHANCE = 15
MAX_HP_PART = 10
LOOT_AGILITY_FACTOR = 0.2
LOOT_HP_FACTOR = 0.5
LOOT_STRENGTH_FACTOR = 0.5

# Параметры 3D-рендеринга и мини-карты
VIEW_3D_FOV = 1.0  # угол обзора в 3D (радианы)
VIEW_3D_DISTANCE = 20.0  # дальность луча для 3D
RAY_STEP = 0.1  # шаг продвижения луча
TURN_ANGLE_STEP = 0.15  # шаг поворота камеры (радианы)
MINIMAP_WIDTH = 25  # ширина мини-карты
MINIMAP_HEIGHT = 13  # высота мини-карты
MINIMAP_OFFSET_X = 2  # смещение мини-карты по X
MINIMAP_OFFSET_Y = 1  # смещение мини-карты по Y
VIEW_3D_OFFSET_Y = 1  # верхний отступ 3D-вида
VISIBILITY_DISTANCE = 6

DOOR_TYPES = ["RED", "GREEN", "BLUE", "YELLOW"]  # Цветные двери
